### ISSUE TITLE
Pre-release version published package containing stacktrace information from developer machine

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/COMET-SDK-Community-Edition#148]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

This is most likely a machine quirk (both of my environment as well as the pre-release nuget SDK build I'm using), but I've somehow managed to get SDK stack traces with file paths from @samatrhea's machine. Probably not a high priority item, but we might want to look into how the SDK is built/packaged. This might be caused by leftover debug .pdb files.

<details>
  <summary>Example stacktrace</summary>

```  
operation
Parameter name: The Thing contained by the Operation does not share the context of the current OperationContainer: thing route: /SiteDirectory/f8a8a10f-6eb2-4ab6-a544-26221066f869 - context: /SiteDirectory/eb77f3e1-a0f3-412d-8ed6-b8ce881c0145

   at CDP4Dal.Operations.OperationContainer.ValidateContextOfOperation(Operation operation) in C:\Users\sgerene\Documents\15-Source-Code\CDP4\CDP4-SDK-Community-Edition\CDP4Dal\Operations\OperationContainer.cs:line 126
   at CDP4Dal.Operations.OperationContainer.AddOperation(Operation operation) in C:\Users\sgerene\Documents\15-Source-Code\CDP4\CDP4-SDK-Community-Edition\CDP4Dal\Operations\OperationContainer.cs:line 110
   at Syncer.Utils.Sync.DomainOfExpertiseSyncer.<Sync>d__1.MoveNext() in C:\Users\User\Desktop\Repositories\CDP4\CDP4-Server-Administration-Tool\Modules\Syncer\Utils\Sync\DomainOfExpertiseSyncer.cs:line 53
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Syncer.ViewModels.SyncerViewModel.<ExecuteSync>d__37.MoveNext() in C:\Users\User\Desktop\Repositories\CDP4\CDP4-Server-Administration-Tool\Modules\Syncer\ViewModels\SyncerViewModel.cs:line 151
```
</details>

### Steps to Reproduce
This can happen for any uncaught exception coming from the mentioned SDK packages version, but as a reproducible example: using a development build of SAT (sha 6a23d120e239d9315e2ae3aba5756f3fad8fa99f - the code on PR #65) by modifying the code in any of the Syncer classes to not properly set the Container property and leaving the exception uncaught.

For example:
<details>
  <summary>DomainOfExpertiseSyncer.cs changes</summary>

```  
            foreach (var domain in this.SourceSiteDirectory.Domain
                .Where(t => selectedIids.Contains((t.Iid))))
            {
                var cloneSourceThing = domain.Clone(true);
                // cloneSourceThing.Container = cloneTargetSiteDirectory; // <- comment this line

                var index = cloneTargetSiteDirectory.Domain
                    .FindIndex(t => t.Iid == cloneSourceThing.Iid);

            ...       
```
</details>

<details>
  <summary>SyncerViewModel.cs changes</summary>

```  
            // try // <- leave the exception uncaught
            // {
                await syncer.Sync(selectedThings);
                UpdateOutput("Sync successful");
            // }
            // catch (Exception e)
            // {
            //     UpdateOutput(e.Message);
            // }
```
</details>

### System Configuration

- CDP4 version:
  - CDP4Common: 6.2.1-2020.10.22.3-pre-release
  - CDP4Dal:  6.2.0-2020.10.22.3-pre-release
  - SAT sha: 6a23d120e239d9315e2ae3aba5756f3fad8fa99f
- .NET Framework version: net452

**Comment by cozminvelciu** [comment]
Do we need to add additional rules or checks on the machine that builds these versions?
